### PR TITLE
Upload CFDE FAIRshake Rubric documentation

### PR DESCRIPTION
**Pull request by dcfcjcheadle**
Uploading the initial converted .md file from google docs.  Still need to finish links in table.  Still need to add images.

### CODE REVIEW

**Comment by dcfcjcheadle** [comment]
The FAIRshake rubric document has been converted from the reviewed google doc to a markdown document.  This addresses nih-cfde/training-and-engagement#38.  I will let you merge into dev post-review and subsequently delete my branch.

**Comment by dcfcjcheadle** [comment]
Just wanted to write a quick note to make sure I'm not dropping the ball here -
I believe we were holding off on finding an appropriate slot in the table of contents before merging this PR back into DEV.  If that's not accurate, please let me know.

**Comment by u8sand** [comment]
Replaced with #47  -- had to do a big merge so wanted to preserve this PR just in-case we needed to get back to it, but we're trying to get this published into the DOCS.

**Comment by ACharbonneau** [comment]
Hey all! I'm not sure if this is documented in this repo, so I just want to make sure you know that Philippe had me set up the documentation site so it pulls from master here. I'm assuming that fits some kind of workflow dev gets pushed to master workflow, but I don't work in this repo generally so I'm not sure how it works.

**Pull request closed without merging**
