### PR TITLE
Decentralizedtoc

### PR DESCRIPTION
**Pull request by ACharbonneau**
Would update the cookbook to use `.pages` files in each folder to automatically build a table of contents for display in the documentation site. It required some rearrangement of the folders under `content`

~A preview of the site is here: https://cfde-published-documentation.readthedocs-hosted.com/en/preview/~
had to take it off the preview branch as it's breaking any other change previews. Let me know if/when you want it back up and I'll re-add it then

### CODE REVIEW

**Comment by ACharbonneau** [comment]
:( it does break a bunch of your code

**Comment by proccaserra** [comment]
@ACharbonneau I can not really merge your PR in this repository as the .pages files required at your end break the jupyterbool build process on our end.

**Comment by ACharbonneau** [comment]
no worries. I have an alternate TOC idea, give me a couple days to make a test branch and we'll see if it works better

**Comment by ACharbonneau** [comment]
no worries. I have an alternate TOC idea, give me a couple days to make a test branch and we'll see if it works better

**Pull request closed without merging**
